version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.9
    commands:
      - pip install -r requirements.txt
  build:
    commands:
      - echo "Build completed"
artifacts:
  files:
    - app.py
    - requirements.txt
    - appspec.yml
    - deploy.s
  discard-paths: yesh
